
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 24 21:28:15 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 22;
  public static final int CONST = 6;
  public static final int SLASH = 36;
  public static final int LPAREN = 7;
  public static final int GREATER = 26;
  public static final int SEMI = 5;
  public static final int CONTINUE = 18;
  public static final int LESS = 31;
  public static final int MINUS = 29;
  public static final int STAR = 27;
  public static final int RPAREN = 8;
  public static final int COMMA = 13;
  public static final int PLUS = 12;
  public static final int EXCLAMATION = 28;
  public static final int AMPERSAND = 35;
  public static final int DOT = 32;
  public static final int FINDANY = 33;
  public static final int EOF = 0;
  public static final int LSBRACE = 34;
  public static final int RETURN = 11;
  public static final int EQUAL = 9;
  public static final int SEARCH = 10;
  public static final int RSBRACE = 25;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int PERCENT = 30;
  public static final int NUMBER = 20;
  public static final int BREAK = 19;
  public static final int IDENT = 21;
  public static final int VOID = 15;
  public static final int LBRACE = 3;
  public static final int READ = 17;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int VERTICALBAR = 24;
  public static final int BOOL_CONST = 23;
  public static final int PRINT = 14;
}

